### PR TITLE
Fix #2: Implement search bar function 

### LINKED ISSUE #2: Search bar not working
The list does not response to search bar input

### PR DESCRIPTION
**Pull request by wasd0109**

### CODE REVIEW

File: src/components/SearchBar.js [hunk 1]
```diff
@@ -1,13 +1,14 @@
 import React from "react";
 
-function SearchBar() {
+function SearchBar({ onSearchChange }) {
```
Comment (wasd0109) [inline src/components/SearchBar.js:3]: Better naming than just onchange

File: src/container/App.js [hunk 2]
```diff
@@ -26,14 +33,16 @@ export class App extends Component {
   }
 
   render() {
-    const { peopleList } = this.state;
+    const filteredRobots = this.state.peopleList.filter((people) =>
+      people.name.toLowerCase().includes(this.state.searchField.toLowerCase())
+    );
```
Comment (wasd0109) [inline src/container/App.js:38]: Is there a better way of doing this?
Maybe a new state to clean it up?
